version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: ecommerce-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  backend:
    # Uses the image from Docker Hub
    image: inshafrajaaei/rynza-backend:latest
    container_name: ecommerce-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    # Variables loaded from the .env file on the server
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_SECRET_KEY=${CLOUDINARY_SECRET_KEY}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  frontend:
    # Uses the image from Docker Hub (Pre-configured with IP via Jenkins)
    image: inshafrajaaei/rynza-frontend:latest
    container_name: ecommerce-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ecommerce-network

  admin-panel:
    # Uses the image from Docker Hub (Pre-configured with IP via Jenkins)
    image: inshafrajaaei/rynza-admin:latest
    container_name: ecommerce-admin
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - ecommerce-network

volumes:
  mongodb_data:

networks:
  ecommerce-network:
    driver: bridge